### ISSUE TITLE
Fix unittest test_max_on_value to pass

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#25]
desc

**Comment by maggienj** [comment]
committed and pushed to new branch issue25
same as issue24 , just needed a name property with a value of "max" in it. 
Also, changed "." to "a"
Test passed.  Committed and pushed.

**Comment by klahnakoski** [comment]
I made an es5 branch on the main repo (https://github.com/klahnakoski/ActiveData/tree/es5). Instead of merging your changes to your es5 branch, you can make pull request from your branch to the main es5 branch.  The pull request process will allow me to see all your changes as a single package, and we can discuss them.  When I merge your pull request, you can then pull origin es5 to get your own changes in your own es5 branch, plus whatever other changes that may have been merged to that branch.

**Comment by klahnakoski** [comment]
The first pull request should come from es5, so that the main es5 is caught up

**Comment by maggienj** [comment]
Agreed. Just created a new pull request from downstream es5 to upstream es5

**Comment by maggienj** [comment]
merged with upstream es5. Closed.
