### ISSUE TITLE
running a sample es query in activedata

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#54]
Running this query, shows some dates in the resultset.

```
{
	"from":"unittest",
	"select":{"value":"run.stats.bytes","aggregate":"max"},
	"edges":["build.platform"],
	"where":{"and":[{"eq":{"etl.id":0}},{"gt":{"run.stats.bytes":600000000}}]}
}


```
there is no reference to date.... looks like some value is getting converted to date and is displayed.... 
still, it puzzles... why it would show dates.
( given that elasticsearch stores dates as long values, the selection of the query doesn't request it to show as dates... so..wondering what causes this date conversion... )
```
build.platform | run.stats.bytes
-- | --
linux32 | 24-Jul-2010 15:51:30


```

**Comment by maggienj** [comment]
or may be that in a doc run.stats.bytes contains a date instead of number of bytes value.

**Comment by klahnakoski** [comment]
ActiveData has no dates, only numbers.  The ActiveData query tool tries to guess if certain numbers are dates (based on the range of the number) and show them as dates.  Since you are viewing very big numbers, they accidentally get shown as dates.  You can click the COPY button, then cut-and-paste the table of data (without date-guessing).

**Comment by klahnakoski** [comment]
For next time, this type of bug can go in the main repo.
